In [1]:
import pandas as pd

In [2]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
citi_bike_data = pd.read_csv('../201909-citibike-tripdata.csv')
citi_bike_df = pd.DataFrame(citi_bike_data)
citi_bike_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,327,2019-09-01 00:00:01.9580,2019-09-01 00:05:29.3410,3733,Avenue C & E 18 St,40.730563,-73.973984,504,1 Ave & E 16 St,40.732219,-73.981656,39213,Subscriber,1968,1
1,1145,2019-09-01 00:00:04.1430,2019-09-01 00:19:09.8360,3329,Degraw St & Smith St,40.682915,-73.993182,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,21257,Customer,1969,0
2,1293,2019-09-01 00:00:07.3090,2019-09-01 00:21:40.7580,3168,Central Park West & W 85 St,40.784727,-73.969617,423,W 54 St & 9 Ave,40.765849,-73.986905,15242,Customer,1969,0
3,1753,2019-09-01 00:00:08.0640,2019-09-01 00:29:21.5040,3299,E 98 St & Park Ave,40.788130,-73.952060,3160,Central Park West & W 76 St,40.778968,-73.973747,38760,Subscriber,1990,1
4,613,2019-09-01 00:00:12.8510,2019-09-01 00:10:26.1850,486,Broadway & W 29 St,40.746201,-73.988557,478,11 Ave & W 41 St,40.760301,-73.998842,32094,Subscriber,1992,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2444895,1764,2019-09-30 23:59:22.7670,2019-10-01 00:28:47.3180,3314,W 95 St & Broadway,40.793770,-73.971888,3161,W 76 St & Columbus Ave,40.780184,-73.977285,41516,Customer,1995,1
2444896,378,2019-09-30 23:59:27.9270,2019-10-01 00:05:46.5700,316,Fulton St & William St,40.709560,-74.006536,327,Vesey Pl & River Terrace,40.715338,-74.016584,31124,Subscriber,1959,2
2444897,561,2019-09-30 23:59:29.1450,2019-10-01 00:08:50.8070,3260,Mercer St & Bleecker St,40.727064,-73.996621,393,E 5 St & Avenue C,40.722992,-73.979955,30285,Customer,1998,1
2444898,311,2019-09-30 23:59:42.2520,2019-10-01 00:04:54.2320,3746,6 Ave & Broome St,40.724308,-74.004730,3435,Grand St & Elizabeth St,40.718822,-73.995960,38290,Subscriber,1989,1
2444899,1500,2019-09-30 23:59:55.3740,2019-10-01 00:24:55.8400,331,Pike St & Monroe St,40.711731,-73.991930,2012,E 27 St & 1 Ave,40.739445,-73.976806,34013,Customer,1969,0

In [3]:
# 2. Check the datatypes of your columns. 
citi_bike_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [4]:
# 3. Convert the 'tripduration' column to datetime datatype.
citi_bike_df['tripduration']= pd.to_datetime(citi_bike_df['tripduration'], unit='s')

In [5]:
# 4. Check the datatypes of your columns. 
citi_bike_df.dtypes
citi_bike_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1970-01-01 00:05:27,2019-09-01 00:00:01.9580,2019-09-01 00:05:29.3410,3733,Avenue C & E 18 St,40.730563,-73.973984,504,1 Ave & E 16 St,40.732219,-73.981656,39213,Subscriber,1968,1
1,1970-01-01 00:19:05,2019-09-01 00:00:04.1430,2019-09-01 00:19:09.8360,3329,Degraw St & Smith St,40.682915,-73.993182,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,21257,Customer,1969,0
2,1970-01-01 00:21:33,2019-09-01 00:00:07.3090,2019-09-01 00:21:40.7580,3168,Central Park West & W 85 St,40.784727,-73.969617,423,W 54 St & 9 Ave,40.765849,-73.986905,15242,Customer,1969,0
3,1970-01-01 00:29:13,2019-09-01 00:00:08.0640,2019-09-01 00:29:21.5040,3299,E 98 St & Park Ave,40.788130,-73.952060,3160,Central Park West & W 76 St,40.778968,-73.973747,38760,Subscriber,1990,1
4,1970-01-01 00:10:13,2019-09-01 00:00:12.8510,2019-09-01 00:10:26.1850,486,Broadway & W 29 St,40.746201,-73.988557,478,11 Ave & W 41 St,40.760301,-73.998842,32094,Subscriber,1992,1

In [8]:
# 5. Export the Dataframe as a new CSV file without the index.
citi_bike_df.to_csv('citi_bike.csv', index=False)